server:
  port: 8089
spring:
  application:
    name: info

  main:
    banner-mode: console

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/person}
    username: ${datasource.username:postgres}
    password: ${datasource.password:postgres}
jwt:
  secret:
    access: ${secret.access:aaaaaa}
    refresh: ${secret.refresh:bbbbbbb}
  expiration:
    access: 10000000
    refresh: 30000000
logging:
  level:
    com.example.myproject.config: debug
    org.springframework.web: debug
springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    operationsSorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true

